//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaiTap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BaiTap()
        {
            this.BaiTapDaNops = new HashSet<BaiTapDaNop>();
        }
    
        public string Ma_bai_tap { get; set; }
        public string Ten_bai_tap { get; set; }
        public string Noi_dung { get; set; }
        public System.DateTime Ngay_giao { get; set; }
        public System.DateTime Ngay_het_han { get; set; }
        public string Ma_lop { get; set; }
        public string Ma_giao_vien { get; set; }
    
        public virtual GiaoVien GiaoVien { get; set; }
        public virtual LopHoc LopHoc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BaiTapDaNop> BaiTapDaNops { get; set; }
    }
}
