//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BangLuong
    {
        public string Ma_bang_luong { get; set; }
        public string Ma_giao_vien { get; set; }
        public string Ten_bang_luon { get; set; }
        public string Noi_dung { get; set; }
        public decimal Luong_co_bang { get; set; }
        public System.DateTime Tu_ngay { get; set; }
        public System.DateTime Den_ngay { get; set; }
        public int So_tiet { get; set; }
        public decimal Tong_nhan { get; set; }
    
        public virtual GiaoVien GiaoVien { get; set; }
    }
}
