//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTiet_TaiLieu
    {
        public string Ma_tai_lieu_lop { get; set; }
        public string Ma_lop { get; set; }
        public string Ma_giao_vien { get; set; }
    
        public virtual LopHoc LopHoc { get; set; }
        public virtual TaiLieu TaiLieu { get; set; }
    }
}
