//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DangKyHoc
    {
        public string Ma_dang_ky { get; set; }
        public string Ma_hoc_vien { get; set; }
        public string Ma_lop { get; set; }
        public string Ma_hoa_don { get; set; }
        public System.DateTime Ngay_dang_ky { get; set; }
    
        public virtual HoaDon HoaDon { get; set; }
        public virtual HocVien HocVien { get; set; }
        public virtual LopHoc LopHoc { get; set; }
    }
}
