//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HoaDon()
        {
            this.DangKyHocs = new HashSet<DangKyHoc>();
        }
    
        public string Ma_hoa_don { get; set; }
        public string Ma_dang_ky { get; set; }
        public System.DateTime Ngay_tao { get; set; }
        public decimal Tong_tien { get; set; }
        public bool Trang_thai_thanh_toan { get; set; }
        public string NgayFormatted
        {
            get { return Ngay_tao.ToString("dd/MM/yyyy"); }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DangKyHoc> DangKyHocs { get; set; }
    }
}
