//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Globalization;
namespace web2.Models
{
    using System;
    using System.Collections.Generic;

    public partial class NguoiDung
    {
        public string Ma { get; set; }
        public string Ho_va_ten { get; set; }
        public System.DateTime Ngay_sinh { get; set; }
       
        public string Sdt { get; set; }
        public string Email { get; set; }
        public string Dia_chi { get; set; }
        public string Tai_khoan { get; set; }
        public string Mat_khau { get; set; }
        public bool Phan_quyen { get; set; }
        List<NguoiDung> ds = new List<NguoiDung>();
        public virtual GiaoVien GiaoVien { get; set; }
        public virtual HocVien HocVien { get; set; }
        public string Ngay_sinh_formatted => Ngay_sinh.ToString("dd/MM/yyyy");

        public List<NguoiDung> khoiTaoNguoiDung(string ma, string hoten, DateTime ngaysinh, string sdt,
            string email, string dia_chi, string taikhoan,string matkhau, bool phanquyen
            )
        {
            ds.Add(new NguoiDung()
            {
                Ma = ma
                , Ho_va_ten = hoten,Ngay_sinh = ngaysinh, Sdt = sdt, Email = email, Dia_chi = Dia_chi,Tai_khoan = taikhoan,Mat_khau = matkhau, Phan_quyen = phanquyen
            }) ;
            return ds;

        }
    }
}
