//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiLieu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaiLieu()
        {
            this.ChiTiet_TaiLieu = new HashSet<ChiTiet_TaiLieu>();
        }
    
        public string Ma_tai_lieu { get; set; }
        public string Ten_tai_lieu { get; set; }
        public string Duong_dan { get; set; }
        public System.DateTime Ngay_upload { get; set; }
        public string Ma_giang_vien { get; set; }
        public string Hoc_vien_duoc_xem { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTiet_TaiLieu> ChiTiet_TaiLieu { get; set; }
        public virtual GiaoVien GiaoVien { get; set; }
        public virtual HocVien HocVien { get; set; }
    }
}
